apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nemesis
  namespace: argocd 
spec:
  project: default
  source:
    path: local/test
    repoURL: 'https://github.com/wambabriand/nemesis-cd'
    targetRevision: main
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: # after 3 minutes pull and apply changes
      selfHeal: true
      prune: true   # Se si cqncella si cancella anche

      # kubectl get secret argocd-initial-admin-secret -n argocd -o yml
      # echo paaa | base64 --decoded

      #kubectl port-forward svc/argocd-server 8081:3000
