apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nemesis
  namespace: argocd 
spec:
  project: default
  sources:
    - path: local/front
      repoURL: 'https://github.com/wambabriand/nemesis-cd'
      targetRevision: main
    - path: local/back
      repoURL: 'https://github.com/wambabriand/nemesis-cd'
      targetRevision: main
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: # after 3 minutes pull and apply changes
      selfHeal: true
      prune: true   # Se si cqncella si cancella anche

      # kubectl get secret argocd-initial-admin-secret -n argocd -o yaml
      # echo paaa | base64 --decoded  OMZXInglpEI1U8Rj

      # kubectl port-forward svc/argocd-server 8080:80
