
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemesis-backend-deployment
  labels:
    app: nemesis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nemesis-backend
  template:
    metadata:
      labels:
        app: nemesis-backend
    spec:
      containers:
      - name: nemesis-backend
        image: briandwamba/nemesis:backend-v0.0.5
        ports:
        - containerPort: 8089
        env:
        - name: POSTGRES_HOST
          value: db-service
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-name
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: nemesis-backend-secret
              key: db-password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-username


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nemesis-backend
  name: nemesis-backend-service
spec:
  type: NodePort
  selector:
    app: nemesis-backend
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
