
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:14.10
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-name
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-host
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nemesis-backend-secret
              key: db-password
        volumeMounts:
          - name: db-pvc
            mountPath: /var/lib/postgresql/data
       
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032
