
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-backend
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:14.10
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: nemesis-backend-configmap
              key: db-host
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nemesis-backend-secret
              key: db-password

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5432
