
apiVersion: v1
kind: ConfigMap
metadata:
  name: lookhere-frontend-configmap
data:
  default.conf: |-
    server {
      listen 80;
      location / {
          alias /usr/share/nginx/html/;
          index index.html;
          try_files $uri $uri/ /index.html = 404;
      }  
      location /api {
        proxy_pass http://lookhere-backend-service:8080/api;
      }
    }
