
apiVersion: v1
kind: ConfigMap
metadata:
  name: nemesis-frontend-configmap
data:
  default.conf: |-
    server {
      listen 80;
      location / {
          alias /usr/share/nginx/html/;
          index index.html;
          try_files $uri $uri/ /index.html = 404;
      }    
      location /api {
          proxy_pass http://nemesis-backend-service:8089/api;
      }
      # listen [::]:443 ssl ipv6only=on; # managed by Certbot
      #  listen 443 ssl; # managed by Certbot
      # ssl_certificate /etc/letsencrypt/live/nemesis-test-wamba.com/fullchain.pem; # managed by Certbot
      # ssl_certificate_key /etc/letsencrypt/live/nemesis-test-wamba.com/privkey.pem; # managed by Certbot
      # include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      
      ssl_session_cache shared:le_nginx_SSL:10m;
      ssl_session_timeout 1440m;
      ssl_session_tickets off;

      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers off;

      ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";

      # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
