apiVersion: apps/v1
kind: Deployment
metadata:
  name: arlette-deployment
  labels:
    app: arlette # important 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arlette
  template:
    metadata:
      labels:
        app: arlette
    spec:
      containers:
      - name: arlette
        image: n
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: arlette-service
  name: arlette-service
spec:
  type: NodePort
  selector:
    app: arlette  # this have to match with the service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
